import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Banner from "@/Components/shared/Banner";
import Navber from "@/Components/shared/Navber";
import Footer from "@/Components/shared/Footer";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <Navber></Navber>


       <main className="flex-1">
       {children}
       <Toaster position="top=right"></Toaster>
       </main>

       <Footer></Footer>


        </body>
    </html>
  );
}
